version: '3'
services:
    apache:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: apache
        depends_on: [ 'mariadb', 'redis', 'rabbitmq', 'mongo' ]
        ports: [ '80:80', '443:443' ]
        volumes: [ '..:/var/www/html' ]
    mariadb:
        image: mariadb
        container_name: mariadb
        ports: [ '3306:3306' ]
        volumes: [ '/var/lib/mysql:/var/lib/mysql' ]
        environment:
            MYSQL_ROOT_PASSWORD: example
        logging:
            driver: none
    redis:
        image: redis
        container_name: redis
        ports: [ '6379:6379' ]
        logging:
            driver: none
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports: [ '5672:5672', '15672:15672' ]
        logging:
            driver: none
    mongo:
        image: mongo
        container_name: mongo
        ports: [ '27017:27017' ]
        logging:
            driver: none
    #scylla:
    #    image: scylladb/scylla
    #    container_name: scylla
    #    ports:
    #      - '9160:9160'
    #    logging:
    #        driver: none
    #elasticsearch:
    #    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    #    container_name: elasticsearch
    #    ports:
    #     - '9200:9200'
    #    logging:
    #        driver: none


