FROM debian:stretch-slim

MAINTAINER Václav Pelíšek <peldax@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# Error: invoke-rc.d: policy-rc.d denied execution of restart.
RUN sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d

# Install core utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    dialog \
    apt-utils \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    openssl \
    gnupg

# Install toolbox
RUN apt-get update && apt-get install -y --no-install-recommends \
    mc \
    git \
    nano \
    htop \
    nmap \
    wget \
    curl

# Add PHP and Node repository
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -

# Install Apache
RUN apt-get update && apt-get install -y --no-install-recommends \
    apache2
RUN a2enmod ssl && \
    a2enmod http2 && \
    a2enmod deflate && \
    a2enmod rewrite && \
    a2enmod include && \
    a2enmod autoindex

RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf


# Install PHP
RUN apt-get update && apt-get install -y --no-install-recommends \
    php7.2 \
    php7.2-cli \
    php7.2-curl \
    php7.2-intl \
    php7.2-gd \
    php7.2-bcmath \
    php7.2-mbstring \
    php7.2-pdo \
    php7.2-json \
    php7.2-zip \
    php7.2-gmp \
    php7.2-xml \
    php7.2-imagick \
    php7.2-igbinary \
    php7.2-mysql \
    php7.2-redis \
    php7.2-mongodb \
    libapache2-mod-php7.2

# Install Composer
ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl -sL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Nodejs
RUN apt-get update && apt-get install -y --no-install-recommends \
    nodejs

# Install Sass
RUN apt-get update && apt-get install -y --no-install-recommends \
    sassc

# Copy configuration
COPY ./apache2/000-default.conf /etc/apache2/sites-enabled/
# SSL certificate
COPY ./ssl/example ./ssl/*.crt /etc/ssl/certs/
COPY ./ssl/example ./ssl/*.key /etc/ssl/private/
# Copy executable files
COPY ./bin/startup.sh /usr/local/bin/
COPY ./bin/composer.sh /usr/local/bin/
COPY ./bin/npm.sh /usr/local/bin/
COPY ./bin/scss.sh /usr/local/bin/
COPY ./bin/js.sh /usr/local/bin/
COPY ./bin/permission.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/composer.sh
RUN chmod +x /usr/local/bin/npm.sh
RUN chmod +x /usr/local/bin/scss.sh
RUN chmod +x /usr/local/bin/js.sh
RUN chmod +x /usr/local/bin/permission.sh

CMD /usr/local/bin/startup.sh

# Enable ports
EXPOSE 80
EXPOSE 443

# Cleanup
RUN rm -rf /var/lib/apt/lists/* && apt-get clean
